### ISSUE TITLE
Awesome job but 1 Typo

### ISSUE THREAD

**Issue by deadcoder0904** [BeeDesignLLC/GlutenProject.com#104]
I know it happens to everyone but its 2018, not 2017

Checkout README 😂

**Comment by deadcoder0904** [comment]
Also, Idk why you would wanna show your Algolia API Key

**Comment by flybayer** [comment]
Haha, thanks, I'll update it!

And the algolia key is read-only for the frontend. Pretty much everyone's algolia key is publicly available.
